### ISSUE TITLE
Gene Search: Shows 'Failed to load data'

### ISSUE THREAD

**Issue by sdash-github** [PeanutBase/jekyll-peanutbase#49]
'Failed to load data' error upon  search for any term, both in dev and prod.  
https://dev.peanutbase.org/tools/gene-keyword-search.html

**Comment by adf-ncgr** [comment]
I think I've fixed it, although I'm a little unclear as to the state of the code. 
The problematic file was
./tools/js/graphql.js
in which on prod I changed it from:
```
// query a local instance of the LIS GraphQL server:
// https://github.com/legumeinfo/graphql-server
const uri = 'https://dev.peanutbase.org/graphql';

```
to 
`
const uri = 'https://www.peanutbase.org/graphql';
`
I thought the graphql endpoint was supposed to be controlled from the _config.yml file, but peanutbase may have diverged early on when that wasn't supported. On dev the problem was simply that the graphql server there had stopped running, so I've restarted it. @svengato I think you still have a TODO here to review the state of the code with respect to using the graphql_uri from the config file.

**Comment by adf-ncgr** [comment]
NB: the use of www.peanutbase.org seems to be needed because otherwise the proxy server returns a redirect that the current code doesn't handle (tries to parse the response as JSON, which it isn't). Not really a problem, just noting it for future reference.

**Comment by svengato** [comment]
> @svengato I think you still have a TODO here to review the state of the code with respect to using the graphql_uri from the config file.

Is that in an issue? I do not see it.

**Comment by adf-ncgr** [comment]
I didn't make a separate issue for it, I just meant that the current issue will probably recur until we move the setting of the graphql endpoint out of code and into config so trying to make sure that the little bandaid I stuck on it is not considered the actual fix.

**Comment by svengato** [comment]
Looking at it now. Is the point to eliminate tools/js/graphql.js ? Because that alone does not work.

**Comment by adf-ncgr** [comment]
no, the point is just to get the value of the uri from config instead of hardcoding; I think it should be similar to how it is done [here](https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/assets/js/graphql/graphql.js#L8)

**Comment by svengato** [comment]
It works now in both development and production. I pulled other recent changes as well (to graphql-server, web-components, jekyll-theme-legumeinfo, and jekyll-peanutbase).
